name: MLB Sheet Update

on:
  # Run at 12:05 AM PST (8:10 AM UTC) every day
  schedule:
    - cron: '5 8 * * *'
  # Optional: Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  update-mlb-sheets:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # Caches pip dependencies

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Firefox
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '135.0.1'

      # Install geckodriver 0.36.0
      - name: Install geckodriver 0.36.0
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xzf geckodriver-v0.36.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      # Create credentials file and MLB env file
      - name: Setup MLB Credentials
        run: |
          echo '${{ secrets.JSON_CREDENTIALS }}' > service-account.json
          echo "JSON_CREDENTIALS=service-account.json" > .mlb.env
          echo "SHEET_ID=${{ secrets.MLB_SHEET_ID }}" >> .mlb.env
          echo "WORKSHEET_GID=${{ secrets.MLB_WORKSHEET_GID }}" >> .mlb.env

      # Run the MLB update script
      - name: Run MLB update script
        run: python mlb_gcp.py

      # Cleanup steps
      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f service-account.json
          rm -f .mlb.env

      - name: Clean up workspace
        if: always()
        run: |
          git clean -fdx
          rm -rf ./*
