name: NBA Sheet Update

on:
  # Run at 12:10 AM PST (8:10 AM UTC) every day
  schedule:
    - cron: '10 8 * * *'
  # Optional: Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  update-nba-sheets:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # Caches pip dependencies

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create credentials file and .env file
      - name: Setup Credentials
        run: |
          echo '${{ secrets.JSON_CREDENTIALS }}' > service-account.json
          echo "JSON_CREDENTIALS=service-account.json" > .env
          echo "SHEET_ID_1=${{ secrets.SHEET_ID_1 }}" >> .env
          echo "WORKSHEET_GID_1=${{ secrets.WORKSHEET_GID_1 }}" >> .env
          echo "SHEET_ID_2=${{ secrets.SHEET_ID_2 }}" >> .env
          echo "WORKSHEET_GID_2=${{ secrets.WORKSHEET_GID_2 }}" >> .env

      # Debugging step (optional)
      - name: Show .env file contents
        run: cat .env

      # Run the NBA update script
      - name: Run NBA update script
        run: python gcp_test.py

      # Cleanup steps
      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f service-account.json
          rm -f .env

      - name: Clean up workspace
        if: always()
        run: |
          git clean -fdx
          rm -rf ./*
